### ISSUE TITLE
提供数据集

### ISSUE THREAD

**Issue by lemon-coder** [taishan1994/pytorch_HAN#1]
您好，可以顺便提供一下测试用的数据集ACM3025.mat吗？

**Comment by taishan1994** [comment]
https://pan.baidu.com/s/1V2iOikRqHPtVvaANdkzROw 提取码：50k2

**Comment by lemon-coder** [comment]
您好，在运行您的main.py时，发现fea_list,biases_list被直接引用，请问这是一个bug吗？

**Comment by taishan1994** [comment]
我还在调试当中，才刚上传到github,现在的是不能正常运行的，建议你先去看下tensorflow版本的以及DGL版本的，目前正在完善readme。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taishan1994/pytorch_HAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月19日(星期六) 晚上8:48
收件人:&nbsp;"taishan1994/pytorch_HAN"<pytorch_HAN@noreply.github.com&gt;;
抄送:&nbsp;"461600371"<461600371@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [taishan1994/pytorch_HAN] 提供数据集 (#1)





 
您好，在运行您的main.py时，发现fea_list,biases_list被直接引用，请问这是一个bug吗？
