### ISSUE TITLE
关于模型实现上的一些疑惑

### ISSUE THREAD

**Issue by YRLT** [taishan1994/pytorch_HAN#2]
您好，最近想把HAN网络构建到自己的一个idea中使用，碰巧看到了您的工作，希望能参考下，但是在模型代码里有一些地方比较困惑想向您请教下：

第一个问题是您复现的HAN网络里元路径这里是怎么定义或计算的？我再代码里似乎没有找到香关的处理过程。

第二个是想确认下HAN网络里关于层级注意力机制的实现您是借用多头注意力机制完成的么？

**Comment by taishan1994** [comment]
第一个问题：本身数据集就提供好了每个节点及其邻居节点，还有其本身的特征，因此是没有元路径的；
第二个问题：是多头注意力，有两种，一种是单种属性的注意力，另一种是不同属性之间的注意力；
好久之前实现的了，有可能不是很正确。

**Comment by YRLT** [comment]
大致明白了，谢谢答复

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年7月7日 21:22
收件人: ***@***.***>
抄送: CARL ***@***.***>; ***@***.***>
主题: Re: [taishan1994/pytorch_HAN] 关于模型实现上的一些疑惑 (#2)


第一个问题：本身数据集就提供好了每个节点及其邻居节点，还有其本身的特征，因此是没有元路径的；
第二个问题：是多头注意力，有两种，一种是单种属性的注意力，另一种是不同属性之间的注意力；
好久之前实现的了，有可能不是很正确。

―

**Comment by jiangmeng12** [comment]
请问有数据预处理的代码吗，不太明白怎么处理数据成后来模样的

**Comment by taishan1994** [comment]
> 请问有数据预处理的代码吗，不太明白怎么处理数据成后来模样的

用的都是标准的数据集，具体使用在utils.py下的load_data_dblp()，你可以看下它数据的格式。

**Comment by jiangmeng12** [comment]
感谢您的回复，我不太清楚他怎么得到的元路径的那个“邻接矩阵的”，请问您知道吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taishan1994/pytorch_HAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taishan1994/pytorch_HAN] 关于模型实现上的一些疑惑 (#2)





  
请问有数据预处理的代码吗，不太明白怎么处理数据成后来模样的
  
用的都是标准的数据集，具体使用在utils.py下的load_data_dblp()，你可以看下它数据的格式。

**Comment by taishan1994** [comment]
> 得到的元路径的那个“邻接矩阵的”，请问您知道吗

邻接矩阵的构建无非就是两个节点之间存在边（关联），那么邻接矩阵对应的位置值就是1，否则就是0

**Comment by jiangmeng12** [comment]
谢谢大佬，可以在请教您一个问题吗，这个代码最后嵌入出来的只是一种类型的节点嘛





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taishan1994/pytorch_HAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 下午5:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taishan1994/pytorch_HAN] 关于模型实现上的一些疑惑 (#2)





  
得到的元路径的那个“邻接矩阵的”，请问您知道吗
  
邻接矩阵的构建无非就是两个节点之间存在边（关联），那么邻接矩阵对应的位置值就是1，否则就是0

**Comment by taishan1994** [comment]
> 谢谢大佬，可以在请教您一个问题吗，这个代码最后嵌入出来的只是一种类型的节点嘛

是的，每个节点分成一类。

**Comment by zyygy** [comment]
你好，大佬，我想知道一下就是您的那个数据集是什么样的呢，如何构成的呢，我这也想研究一下您的代码，想构成一个异构图，但是我在mablab中没办法可视化这个东西，我想咨询一下怎么构成的那个异构图。然后我跑了一下您这个代码，为什么测试准确率这么低呢？
![@X$RB_U}Q%`QYP (@ W2](https://github.com/taishan1994/pytorch_HAN/assets/96367517/57a76d8c-ca47-4d89-ba0c-19d9d7217502)

**Comment by taishan1994** [comment]
> 你好，大佬，我想知道一下就是您的那个数据集是什么样的呢，如何构成的呢，我这也想研究一下您的代码，想构成一个异构图，但是我在mablab中没办法可视化这个东西，我想咨询一下怎么构成的那个异构图。然后我跑了一下您这个代码，为什么测试准确率这么低呢？ ![@X$RB_U}Q%`QYP (@ W2](https://private-user-images.githubusercontent.com/96367517/289555114-57a76d8c-ca47-4d89-ba0c-19d9d7217502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDc1MTAsIm5iZiI6MTcwMjM0NzIxMCwicGF0aCI6Ii85NjM2NzUxNy8yODk1NTUxMTQtNTdhNzZkOGMtY2E0Ny00ZDg5LWJhMGMtMTlkOWQ3MjE3NTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyMTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzMxYjFhOWI5ZjRhYzUwNTMwMmM0OTJjZTkxYjUzYWU2ZTliYzg1MzZhYjNlYjE5YzYyYzEzZTUxYzhlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L-syzBu44cmaQiUzS8knm7CZOsII2bGG3n8qS37TR2M)

数据是现有的额，这个看readme里面第一部分，调换下测试集和训练集。
