### ISSUE TITLE
对模型的输入biases_list和adj_to_bias方法的疑惑

### ISSUE THREAD

**Issue by coolzc** [taishan1994/pytorch_HAN#3]
对adj_to_bias方法里有两个疑惑：
1. mt[g] = np.matmul(mt[g], (adj[g] + np.eye(adj.shape[1])))这个相乘是什么意思，为什么邻接矩阵的对角线要为1然后去和 一个np.empty初始化后的矩阵相乘？
2. 对mt[g][i][j] > 0.0的元素赋值为1，然后最后返回-1e9 * (1.0 - mt)，这个操作是什么意义？

得到了biases_list目的是什么呢？

**Comment by taishan1994** [comment]
> 对adj_to_bias方法里有两个疑惑：
> 
> 1. mt[g] = np.matmul(mt[g], (adj[g] + np.eye(adj.shape[1])))这个相乘是什么意思，为什么邻接矩阵的对角线要为1然后去和 一个np.empty初始化后的矩阵相乘？
> 2. 对mt[g][i][j] > 0.0的元素赋值为1，然后最后返回-1e9 * (1.0 - mt)，这个操作是什么意义？
> 
> 得到了biases_list目的是什么呢？

1、类似于全连接层中的偏置项吧。
2、后面那个应该是在计算注意力的时候，忽略掉为0.0的部分。

**Comment by coolzc** [comment]
谢谢了，我后来发现作者用的是GAT的代码，看了GAT自然就理解了
